version: '2'
services:
  registry:
    container_name: talos-registry
    restart: always
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_LOG_ACCESSLOG_DISABLED: "false"
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
    networks:
      registry:
        ipv4_address: 10.11.0.11

  mitmproxy:
    container_name: talos-mitmproxy
    restart: always
    image: mitmproxy/mitmproxy
    command:
      - mitmweb
      - --web-host
      - 0.0.0.0
      - --showhost
      - --ssl-insecure
    volumes:
      - ./certs:/home/mitmproxy/.mitmproxy
    networks:
      registry:
        ipv4_address: 10.11.0.12

networks:
  registry:
    external: 
      name: my-cluster
